### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by emreozkangit** [DennyZhang/challenges-kubernetes#1]
**hi denny,
I am trying to do your challange.When I use this yaml file,I got an error.Dbserver is CrashLoopBackOff .But I changed the image mysql to mariadb.Its ok.FYI**

NAME                                   READY     STATUS    RESTARTS   AGE
dbclient-deployment-860309613-dq9ds    1/1       Running   0          12s
dbclient-deployment-860309613-f1bcl    1/1       Running   0          12s
dbserver-deployment-2982927993-vlvql   0/1       Error     0          12s

**Then,**

dbclient-deployment-860309613-f1bcl    1/1       Running            0          14s
dbserver-deployment-2982927993-vlvql   0/1       CrashLoopBackOff   1          14s

**I examined log.**

@kubernetes-191507:~$ kubectl logs dbserver-deployment-2982927993-vlvql
Initializing database
2018-01-08T11:00:46.934582Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-01-08T11:00:46.936388Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2018-01-08T11:00:46.936597Z 0 [ERROR] Aborting

**It said that I should use explicit_defaults_for_timestamp server parameter.But I cant find any documentation about how to use with yaml file.**

**Comment by dennyzhang** [comment]
@emreozkangit thanks for trying!

I guess you're in Scenario-103, right? I just tried it. 

Doesn't seem to be able to reproduce the issue.

**Comment by emreozkangit** [comment]
Scenario-102
  I am Using GCE container engine.

**Comment by dennyzhang** [comment]
Tried Scenario-102 with minikube.  Haven't tried in GCE.
Anyway mariadb should be more preferred than mysql image.

Thanks, @emreozkangit. Let me change it and give it another try. 

macs-MacBook-Pro:Scenario-102 mac$ kubectl get pods
NAME                                   READY     STATUS    RESTARTS   AGE
dbclient-deployment-69844df475-58tph   1/1       Running   0          34s
dbclient-deployment-69844df475-5ssdl   1/1       Running   0          34s
dbserver-deployment-6f9657c869-x29ff   1/1       Running   0          34s
